src/objects/IPTracker__c.object
<CustomObject>
    <fields>
        <fullName>IP_Address__c</fullName>
        <label>IP Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>IPTracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>IPTracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPTrackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrackIp.cls
public class TrackIp{
    
    public TrackIp(){
        Apexpages.currentPage().getHeaders().put('Access-Control-Allow-Origin','*');
    }
    public void createIp(){
        system.debug('hello');
        IPTracker__c tr = new IPTracker__c();
        //tr.IP_Address__c = ApexPages.currentPage().getParameters().get('ip');
         tr.IP_Address__c = Apexpages.currentpage().getHeaders().get('X-Salesforce-SIP');
        insert tr;

    }
}